# see https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md for docs

# MD004 - Unordered list style
# We want to use dashes consistently everywhere
MD004:
  style: dash
# MD007 - Unordered list indentation
# To prevent conflict between apps modifying markdown files
MD007:
  indent: 4
# MD013 - Line length
# Do not artificially limit line length in a language in markdown
# because of the way it handles whitespaces, like line wrapping.
MD013: false
# MD033 - Inline HTML
MD033:
  allowed_elements:
    - details # there is no markdown equivalent for accordions
    - summary # there is no markdown equivalent for accordions
    - br
