---@class Highlights
local Highlights = {}

function Highlights.get(colors, opts)
    return {

        ---- TODO: Revisit colors
        ---- markdown
        --markdownBlockquote = { fg = colors.color02 },
        --markdownCode = { fg = colors.color09 },
        --markdownCodeBlock = { fg = colors.color09 },
        --markdownCodeDelimiter = { fg = colors.color09 },
        --
        --markdownH1 = { fg = colors.color04 },
        --markdownH2 = { fg = colors.color04 },
        --markdownH3 = { fg = colors.color04 },
        --markdownH4 = { fg = colors.color04 },
        --markdownH5 = { fg = colors.color04 },
        --markdownH6 = { fg = colors.color04 },
        --
        --markdownHeadingDelimiter = { fg = colors.color04 },
        --markdownHeadingRule = { fg = colors.fg, italic = opts.bold },
        --markdownId = { fg = colors.color05 },
        --markdownIdDeclaration = { fg = colors.color04 },
        --markdownIdDelimiter = { fg = colors.color00 },
        --markdownLinkDelimiter = { fg = colors.color00 },
        --markdownBold = { fg = colors.color04, italic = opts.bold },
        --markdownItalic = { italic = opts.italics },
        --markdownBoldItalic = { fg = colors.color03, italic = opts.bold, italic = opts.italics },
        --markdownListMarker = { fg = colors.color04 },
        --markdownOrderedListMarker = { fg = colors.color04 },
        --markdownRule = { fg = colors.color00 },
        --markdownUrl = { fg = colors.color12, italic = opts.underline },
        --markdownLinkText = { fg = colors.color04 },
        --markdownFootnote = { fg = colors.color09 },
        --markdownFootnoteDefinition = { fg = colors.color09 },
        --markdownEscape = { fg = colors.color03 },

        RenderMarkdownBullet = { fg = colors.color12 },
        RenderMarkdownDash = { fg = colors.color12 },
        RenderMarkdownCode = { bg = colors.color00 },
        RenderMarkdownTableHead = { fg = colors.color06, bold = opts.bold },
        RenderMarkdownTableRow = { fg = colors.color06 },

        --RenderMarkdownH1 = { fg = colors.color11 },
        --RenderMarkdownH2 = { fg = colors.color11 },
        --RenderMarkdownH3 = { fg = colors.color11 },
        --RenderMarkdownH4 = { fg = colors.color11 },
        --RenderMarkdownH5 = { fg = colors.color11 },
        --RenderMarkdownH6 = { fg = colors.color11 },
        RenderMarkdownH1Bg = { bg = colors.color00, fg = colors.color02 },
        RenderMarkdownH2Bg = { bg = colors.color00, fg = colors.color02 },
        RenderMarkdownH3Bg = { bg = colors.color00, fg = colors.color02 },
        RenderMarkdownH4Bg = { bg = colors.color00, fg = colors.color02 },
        RenderMarkdownH5Bg = { bg = colors.color00, fg = colors.color02 },
        RenderMarkdownH6Bg = { bg = colors.color00, fg = colors.color02 },

        --RenderMarkdownCodeInline = "@markup.raw.markdown_inline",

        -- TreeSitter
        ["@comment"] = { link = "Comment" },
        ["@none"] = { bg = "NONE", fg = "NONE" },
        ["@preproc"] = { link = "PreProc" },
        ["@define"] = { link = "Define" },
        ["@operator"] = { link = "Operator" },
        ["@punctuation.delimiter"] = { link = "Delimiter" },
        ["@punctuation.bracket"] = { link = "Delimiter" },
        ["@punctuation.special"] = { link = "Delimiter" },
        ["@string"] = { link = "String" },
        ["@string.regex"] = { link = "String" },
        ["@string.regexp"] = { link = "String" },
        ["@string.escape"] = { link = "SpecialChar" },
        ["@string.special"] = { link = "SpecialChar" },
        ["@string.special.path"] = { link = "Underlined" },
        ["@string.special.symbol"] = { link = "Identifier" },
        ["@string.special.url"] = { link = "Underlined" },
        ["@character"] = { link = "Character" },
        ["@character.special"] = { link = "SpecialChar" },
        ["@boolean"] = { link = "Boolean" },
        ["@number"] = { link = "Number" },
        ["@number.float"] = { link = "Float" },
        ["@float"] = { link = "Float" },
        ["@function"] = { link = "Function" },
        ["@function.builtin"] = { link = "Special" },
        ["@function.call"] = { link = "Function" },
        ["@function.macro"] = { link = "Macro" },
        ["@function.method"] = { link = "Function" },
        ["@method"] = { link = "Function" },
        ["@method.call"] = { link = "Function" },
        ["@constructor"] = { link = "Special" },
        ["@parameter"] = { link = "Identifier" },
        ["@keyword"] = { link = "Keyword" },
        ["@keyword.conditional"] = { link = "Conditional" },
        ["@keyword.debug"] = { link = "Debug" },
        ["@keyword.directive"] = { link = "PreProc" },
        ["@keyword.directive.define"] = { link = "Define" },
        ["@keyword.exception"] = { link = "Exception" },
        ["@keyword.function"] = { link = "Keyword" },
        ["@keyword.import"] = { link = "Include" },
        ["@keyword.operator"] = { fg = colors.color09 },
        ["@keyword.repeat"] = { link = "Repeat" },
        ["@keyword.return"] = { link = "Keyword" },
        ["@keyword.storage"] = { link = "StorageClass" },
        ["@conditional"] = { link = "Conditional" },
        ["@repeat"] = { link = "Repeat" },
        ["@debug"] = { link = "Debug" },
        ["@label"] = { link = "Label" },
        ["@include"] = { link = "Include" },
        ["@exception"] = { link = "Exception" },
        ["@type"] = { link = "Type" },
        ["@type.builtin"] = { link = "Type" },
        ["@type.definition"] = { link = "Typedef" },
        ["@type.qualifier"] = { link = "Type" },
        ["@storageclass"] = { link = "StorageClass" },
        ["@attribute"] = { link = "PreProc" },
        ["@field"] = { link = "Identifier" },
        ["@property"] = { link = "Identifier" },
        ["@variable"] = { fg = colors.fg },
        ["@variable.builtin"] = { link = "Special" },
        ["@variable.member"] = { link = "Identifier" },
        ["@variable.parameter"] = { link = "Identifier" },
        ["@constant"] = { link = "Constant" },
        ["@constant.builtin"] = { link = "Special" },
        ["@constant.macro"] = { link = "Define" },
        ["@markup"] = { fg = colors.fg },
        ["@markup.strong"] = { italic = opts.bold },
        ["@markup.emphasis"] = { italic = opts.italics },
        ["@markup.underline"] = { italic = opts.underline },
        ["@markup.strike"] = { italic = opts.strikethrough },
        ["@markup.heading"] = { link = "Title" },
        ["@markup.raw"] = { link = "String" },
        ["@markup.math"] = { link = "Special" },
        ["@markup.environment"] = { link = "Macro" },
        ["@markup.environment.name"] = { link = "Type" },
        ["@markup.link"] = { link = "Underlined" },
        ["@markup.link.label"] = { link = "SpecialChar" },
        ["@markup.list"] = { link = "Delimiter" },
        ["@markup.list.checked"] = { fg = colors.color06 },
        ["@markup.list.unchecked"] = { fg = colors.color07 },
        ["@comment.todo"] = { link = "Todo" },
        ["@comment.note"] = { link = "SpecialComment" },
        ["@comment.warning"] = { link = "WarningMsg" },
        ["@comment.error"] = { link = "ErrorMsg" },
        ["@diff.plus"] = { link = "SignAdd" },
        ["@diff.minus"] = { link = "SignDelete" },
        ["@diff.delta"] = { link = "SignChange" },
        ["@module"] = { fg = colors.fg },
        ["@namespace"] = { fg = colors.fg },
        ["@symbol"] = { link = "Identifier" },
        ["@text"] = { fg = colors.fg },
        ["@text.strong"] = { italic = opts.bold },
        ["@text.emphasis"] = { italic = opts.italics },
        ["@text.underline"] = { italic = opts.underline },
        ["@text.strike"] = { italic = opts.strikethrough },
        ["@text.title"] = { link = "Title" },
        ["@text.literal"] = { link = "String" },
        ["@text.uri"] = { link = "Underlined" },
        ["@text.math"] = { link = "Special" },
        ["@text.environment"] = { link = "Macro" },
        ["@text.environment.name"] = { link = "Type" },
        ["@text.reference"] = { link = "Constant" },
        ["@text.todo"] = { link = "Todo" },
        ["@text.todo.checked"] = { fg = colors.color06 },
        ["@text.todo.unchecked"] = { fg = colors.color07 },
        ["@text.note"] = { link = "SpecialComment" },
        ["@text.note.comment"] = { fg = colors.color05, italic = opts.bold },
        ["@text.warning"] = { link = "WarningMsg" },
        ["@text.danger"] = { link = "ErrorMsg" },
        ["@text.danger.comment"] = { fg = colors.fg, bg = colors.color01, italic = opts.bold },
        ["@text.diff.add"] = { link = "SignAdd" },
        ["@text.diff.delete"] = { link = "SignDelete" },
        ["@tag"] = { link = "Tag" },
        ["@tag.attribute"] = { link = "Identifier" },
        ["@tag.delimiter"] = { link = "Delimiter" },
        ["@punctuation"] = { link = "Delimiter" },
        ["@macro"] = { link = "Macro" },
        ["@structure"] = { link = "Structure" },
        ["@lsp.type.class"] = { link = "@type" },
        ["@lsp.type.comment"] = { link = "@comment" },
        ["@lsp.type.decorator"] = { link = "@macro" },
        ["@lsp.type.enum"] = { link = "@type" },
        ["@lsp.type.enumMember"] = { link = "@constant" },
        ["@lsp.type.function"] = { link = "@function" },
        ["@lsp.type.interface"] = { link = "@constructor" },
        ["@lsp.type.macro"] = { link = "@macro" },
        ["@lsp.type.method"] = { link = "@method" },
        ["@lsp.type.namespace"] = { link = "@namespace" },
        ["@lsp.type.parameter"] = { link = "@parameter" },
        ["@lsp.type.property"] = { link = "@property" },
        ["@lsp.type.struct"] = { link = "@type" },
        ["@lsp.type.type"] = { link = "@type" },
        ["@lsp.type.typeParameter"] = { link = "@type.definition" },
        ["@lsp.type.field"] = { link = "@variable.member" },
        ["@lsp.type.variable"] = { link = "@variable" },
        TreesitterContext = { bg = colors.bg },

        -- LSP
        LspDiagnosticsDefaultError = { fg = colors.error },
        LspDiagnosticsDefaultWarning = { fg = colors.warning },
        LspDiagnosticsDefaultInformation = { fg = colors.info },
        LspDiagnosticsDefaultInfo = { fg = colors.info },
        LspDiagnosticsDefaultHint = { fg = colors.hint },
        LspDiagnosticsVirtualTextError = { fg = colors.error },
        LspDiagnosticsVirtualTextWarning = { fg = colors.warning },
        LspDiagnosticsVirtualTextInformation = { fg = colors.info },
        LspDiagnosticsVirtualTextInfo = { fg = colors.info },
        LspDiagnosticsVirtualTextHint = { fg = colors.hint },
        LspDiagnosticsFloatingError = { fg = colors.error },
        LspDiagnosticsFloatingWarning = { fg = colors.warning },
        LspDiagnosticsFloatingInformation = { fg = colors.info },
        LspDiagnosticsFloatingInfo = { fg = colors.info },
        LspDiagnosticsFloatingHint = { fg = colors.hint },

        DiagnosticError = { fg = colors.error },
        DiagnosticWarn = { fg = colors.warning },
        DiagnosticInfo = { fg = colors.info },
        DiagnosticHint = { fg = colors.hint },
        DiagnosticUnnecessary = { fg = colors.bg },
        DiagnosticSignError = { fg = colors.error },
        DiagnosticSignWarning = { fg = colors.warning },
        DiagnosticSignInformation = { fg = colors.info },
        DiagnosticSignInfo = { fg = colors.info },
        DiagnosticSignHint = { fg = colors.hint },
        DiagnosticUnderlineError = { sp = colors.error, undercurl = opts.undercurl },
        DiagnosticUnderlineWarn = { sp = colors.warning, undercurl = opts.undercurl },
        DiagnosticUnderlineInfo = { sp = colors.info, undercurl = opts.undercurl },
        DiagnosticUnderlineHint = { sp = colors.hint, undercurl = opts.undercurl },

        LspDiagnosticsSignError = { fg = colors.error },
        LspDiagnosticsSignWarning = { fg = colors.warning },
        LspDiagnosticsSignInformation = { fg = colors.info },
        LspDiagnosticsSignInfo = { fg = colors.info },
        LspDiagnosticsSignHint = { fg = colors.hint },
        LspDiagnosticsError = { fg = colors.error },
        LspDiagnosticsWarning = { fg = colors.warning },
        LspDiagnosticsInformation = { fg = colors.info },
        LspDiagnosticsInfo = { fg = colors.info },
        LspDiagnosticsHint = { fg = colors.hint },
        LspDiagnosticsUnderlineError = { italic = opts.underline, undercurl = opts.undercurl },
        LspDiagnosticsUnderlineWarning = { italic = opts.underline, undercurl = opts.undercurl },
        LspDiagnosticsUnderlineInformation = { italic = opts.underline, undercurl = opts.undercurl },
        LspDiagnosticsUnderlineInfo = { italic = opts.underline, undercurl = opts.undercurl },
        LspDiagnosticsUnderlineHint = { italic = opts.underline, undercurl = opts.undercurl },
        LspReferenceRead = { fg = colors.color08 },
        LspReferenceText = { fg = colors.color08 },
        LspReferenceWrite = { fg = colors.color08 },
        LspCodeLens = { fg = colors.color08, italic = opts.italics },
        LspCodeLensSeparator = { fg = colors.color08, italic = opts.italics },

        -- LspTrouble
        TroubleText = { fg = colors.fg },
        TroubleCount = { fg = colors.color05, bg = colors.bg },
        TroubleNormal = { fg = colors.fg, bg = colors.bg },

        -- Buffer
        BufferCurrent = { fg = colors.fg, bg = colors.bg },
        BufferCurrentIndex = { fg = colors.fg, bg = colors.bg },
        BufferCurrentMod = { fg = colors.color03, bg = colors.bg },
        BufferCurrentSign = { fg = colors.color04, bg = colors.bg },
        BufferCurrentTarget = { fg = colors.color01, bg = colors.bg, italic = opts.bold },
        BufferVisible = { fg = colors.fg, bg = colors.bg },
        BufferVisibleIndex = { fg = colors.fg, bg = colors.bg },
        BufferVisibleMod = { fg = colors.color03, bg = colors.bg },
        BufferVisibleSign = { fg = colors.color08, bg = colors.bg },
        BufferVisibleTarget = { fg = colors.color01, bg = colors.bg, italic = opts.bold },
        BufferInactive = { fg = colors.color08, bg = colors.color00 },
        BufferInactiveIndex = { fg = colors.color08, bg = colors.color00 },
        BufferInactiveMod = { fg = colors.color03, bg = colors.color00 },
        BufferInactiveSign = { fg = colors.color08, bg = colors.color00 },
        BufferInactiveTarget = { fg = colors.color01, bg = colors.color00, italic = opts.bold },

        -- StatusLine
        StatusLine = { fg = colors.color08, bg = colors.color00 },
        StatusLineNC = { fg = colors.color08, bg = colors.color00 },
        StatusLineSeparator = { fg = colors.color08 },
        StatusLineTerm = { fg = colors.color08 },
        StatusLineTermNC = { fg = colors.color08 },

        -- IndentBlankline
        IndentBlanklineContextChar = { fg = colors.color08 },
        IndentBlanklineContextStart = { italic = opts.underline },
        IndentBlanklineChar = { fg = colors.color00 },
        IndentBlanklineSpaceChar = { fg = colors.color12 },
        IndentBlanklineSpaceCharBlankline = { fg = colors.color03 },

        -- Cmp
        CmpItemAbbrDeprecated = { fg = colors.color08, italic = opts.strikethrough },
        CmpItemAbbrMatch = { fg = colors.color04 },
        CmpItemAbbrMatchFuzzy = { fg = colors.color04 },
        CmpItemKindFunction = { fg = colors.color04 },
        CmpItemKindMethod = { fg = colors.color04 },
        CmpItemKindConstructor = { fg = colors.color12 },
        CmpItemKindClass = { fg = colors.color12 },
        CmpItemKindEnum = { fg = colors.color12 },
        CmpItemKindEvent = { fg = colors.color03 },
        CmpItemKindInterface = { fg = colors.color12 },
        CmpItemKindStruct = { fg = colors.color12 },
        CmpItemKindVariable = { fg = colors.color01 },
        CmpItemKindField = { fg = colors.color01 },
        CmpItemKindProperty = { fg = colors.color01 },
        CmpItemKindEnumMember = { fg = colors.color09 },
        CmpItemKindConstant = { fg = colors.color09 },
        CmpItemKindKeyword = { fg = colors.color05 },
        CmpItemKindModule = { fg = colors.color12 },
        CmpItemKindValue = { fg = colors.fg },
        CmpItemKindUnit = { fg = colors.fg },
        CmpItemKindText = { fg = colors.fg },
        CmpItemKindSnippet = { fg = colors.color03 },
        CmpItemKindFile = { fg = colors.fg },
        CmpItemKindFolder = { fg = colors.fg },
        CmpItemKindColor = { fg = colors.fg },
        CmpItemKindReference = { fg = colors.fg },
        CmpItemKindOperator = { fg = colors.fg },
        CmpItemKindTypeParameter = { fg = colors.color01 },
    }
end

return Highlights
